### ISSUE TITLE
Gestion de la concurrence

### ISSUE THREAD

**Issue by gabrielvv** [Lucieo/esquisse-back#2]
Aujourd'hui c'est le serveur qui envoie l'ordre de publier la page actuellement dessinée/devinée aux clients par une subscription SUBMIT_PAGE. Il reçoit les réponses et contrôle à chaque fois qu'il en reçoit une si il a bien toutes les réponses. Si c'est le cas il augmente le numéro du tour et envoie une subscription GAME_UPDATE aux clients avec les nouvelles valeurs de jeu pour passer au tour suivant. Problème : si il reçoit les submit pages de chaque client en même temps il valide plusieurs fois que le tour est complet et envoie plusieurs ordres SUBMIT_PAGE. Pour le moment ça ne gène pas le jeu mais c'est du gâchis de call. Y-a-t-il un moyen plus propre de gérer ces envois concomitants?

**Comment by gabrielvv** [comment]
> le tour est complet et envoie plusieurs ordres SUBMIT_PAGE

@Lucieo Est ce que ce n'est pas plutôt GAME_UPDATE ?

**Comment by gabrielvv** [comment]
Dans tous les cas, je vois un potentiel bug ici: https://github.com/Lucieo/esquisse-back/blob/82abad7843b8792439b4639c997d22dd0e3096fe/models/game.js#L31

Si la fonction est exécuté en parallèle:
1. A lit *game.turn = 5*
2. B lit *game.turn = 5*
3. A incrémente *game.turn* et sauvegarde
4. B incrémente *game.turn* et sauvegarde
5. *game.turn = 6* dans la base de données

**Comment by gabrielvv** [comment]
En code, ça donne ça:
```js
const unsafeIncrement = async () => {
    const game = await Game.findById(gameId);
    game.turn = +game.turn + 1;
    await game.save()
}

const safeIncrement = async () => {
    await Game.findOneAndUpdate({
        _id: gameId
   // turn doit être un Number dans le schema
    }, { $inc: { turn: 1 } });
}
```

**Comment by gabrielvv** [comment]
- https://docs.mongodb.com/manual/reference/operator/update/inc/
- http://mongodb.github.io/node-mongodb-native/3.5//api/Collection.html#findOneAndUpdate

**Comment by Lucieo** [comment]
En effet c'est potentiellement un risque mais je n'ai encore jamais eu le bug en test. Par contre ce que je vois c'est plusieurs call SUBMIT_PAGE envoyés au client en front à chaque fois car chaque enregistrement lance un setimeout avec un call sur le chanel de subscription SUBMIT_PAGE. Ex 3 clients postent le mot initial en même temps = 3 états de complétion du game = 3 setimeout lancés pour le dessin = 3 call SUBMIT_PAGE reçus en front à la fin du tour du dessin. Pour le moment ça n'empêche pas le fonctionnement du jeu mais c'est pas du tout optimisé. Et en effet ça pourrait créer un bug de tour augmenté trois fois, d'ailleurs je ne comprends pas pourquoi ça n'est pas encore arrivé

**Comment by Lucieo** [comment]
L'effet observé c'est plusieurs call SUBMIT_PAGE envoyés au client en front à chaque fois car chaque enregistrement lance un setimeout avec un call sur le chanel de subscription SUBMIT_PAGE. Ex 3 clients postent le mot initial en même temps = 3 états de complétion du game = 3 setimeout lancés pour le dessin = 3 call SUBMIT_PAGE reçus en front à la fin du tour du dessin. Pour le moment ça n'empêche pas le fonctionnement du jeu mais c'est pas du tout optimisé. 

Pour la question du tour ça n'est pas un problème d'avoir 6 au lieu de 7 car il ne doit être augmenté que de 1 unité même si appelé par 3 clients. Ce qui détermine le passage au prochain tour (celui qui donnera à chacun un nouveau sketchbook avec un dessin ou un mot du voisin) c'est le fait d'avoir reçu toutes les réponses. Donc on veut que ça soit 6 et non 7 sinon ça bousculera l'ordre d'attribution des sketchbooks aux joueurs en sautant un tour. En front 
le tour est utilisé en étant additionné à l'index du joueur dans la liste pour trouver l'index du sketchbook à lui associer. A chaque tour supplémentaire il est décalé d'une unité et prends donc le sketchbook du voisin.

**Comment by gabrielvv** [comment]
1. Est ce que tu peux pointer le code concerné? je ne vois toujours pas où ça se passe. J'ai l'impression qu'on parle plutôt de TIME_TO_SUBMIT:  
https://github.com/Lucieo/esquisse-back/blob/6a969906098a7317c5c82c57b488b63c19bcc642/models/game.js#L50

**Comment by gabrielvv** [comment]
2. J'étais complètement à côté de la plaque :sweat_smile:

**Comment by Lucieo** [comment]
1=> Oui pardon TIME_TO_SUBMIT exactement ça
